from functions import *
from cobra.io import write_sbml_model

'''
fixing the reactions where a lot of carbon, oxygen, hydrogen goes missing look at the Excel files generated by 
the function print_model_2_excel (see script check_element_balance.py)
to see which reactions are leaking certain elements 
'''

modelName = "P_sherm_model.xml"
loc_sher = get_location(modelName)
model = cobra.io.read_sbml_model(loc_sher)
model.name = "P_sherm_model"

# bioMass metabolite does not have a name
metbiomassId = 'S_biomass_ext'
metbiomass = model.metabolites.get_by_id(metbiomassId)
metbiomass.name = 'Biomass'


''' 
let's go for low hanging fruit:
let's estimate the formulas of metabolites (that are missing a formula) with a reaction of your choosing (see Excel analysis)
'''
fixDict = {
     #'S_cpdnew27_c0':'rxnnew67_c0',     # Propionibacterium cell wall
     'S_cpdnew22_c0': 'rxnnew66_c0',     # Propionibacterium peptidoglycan
     'S_cpdnew20_c0': 'rxnnew64_c0',     # Polysacaride
	 'S_cpdnew26_c0': 'rxnnew72_c0',     # Small molecule pool
	 'S_cpdnew21_c0': 'rxnnew65_c0'      # Lipomannan
}
estimate = estimate_formula(model= model, estimationDict= fixDict)

# todo declare the correct metabolite formula

# let's look at the reaction which cause a significant loss of carbon (see the analysis Excel files)
rxnId = ["rxnnew63_c0",
"rxnnew66_c0",
"rxnnew73_c0",
"rxnnew74_c0"]

for id in rxnId:
     check_reaction(model= model, reactionID= id)

#having looked at the reactions, lets fix the formulas of the metabolites so that massbalances comply
# the stoichometry of all the interested metabolites are one, so just add the missing elements to the formula
metFormulas = {
     'S_cpdnew19_c0': 'C29H33O28',                     # UDP-2,3-diacetamido-2,3-dideoxy-D-mannuronate, no formula
     'S_cpdnew22_c0': 'C58.64H89.28O46.128',           # Propionibacterium peptidoglycan, no formula
     'S_cpd11463_c0': 'C4H5N2O3C33.17H31.847O18.512',  # protein , C4H5N2O3R2 , replace the R
     'S_cpd11613_c0': 'C15H23O19P3C16.66H11.46O2.876'  # RNA, C15H23O19P3R3 , replace the R
}

# let's give a correct formula to each molecule
for id in metFormulas:
     met = model.metabolites.get_by_id(id)
     met.formula = metFormulas[id]

#write_sbml_model(model, "screening junk/P_sherm_model_test.xml")
print_SBML_info_2_excel(modelName=model, saveName= 'test.xlsx')